function transImg = imgTransform(inputImg, imgSize, transMatrix, transModel)

transform = maketform(transModel, [transMatrix(1) transMatrix(3) 0; ...
    transMatrix(2) transMatrix(4) 0; transMatrix(5) transMatrix(6) 1]);
transImg = imtransform(inputImg, transform, ...
                            'FillValues', 255, ...
                            'XData', [1 imgSize(2)], ...
                            'YData', [1 imgSize(1)]);
                        